version: '3.8'

services:
    wordle-backend:
        build: .
        container_name: wordle-backend
        ports:
            - '5001:5001'
        environment:
            - NODE_ENV=development
        volumes:
            - .:/app
            - /app/node_modules
        command: npm start
