version: '3'
services:
    app:
        image: node:16
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
        ports:
            - '5000:5000'
        command: npm start
        environment:
            - NODE_ENV=development
